package fake

import (
	"bytes"
	"fmt"

	"aegis/internal/provider"
)

// FakeProvider implements the Provider interface for testing failure scenarios.
type FakeProvider struct {
	ProviderName   string
	Protocol       string
	ProvConfigPath string

	// Failure injection matrix
	MissingBinary          bool
	FailValidate           bool
	ValidateErr            string
	FailReload             bool
	ReloadErr              string
	FailBackup             bool
	FailRestore            bool
	RuntimeVerifyFailed    bool
	RuntimeVerifyErr       string
	ListenerConflict       bool
	ListenerConflictDetail string
	ConfigFileMissing      bool
	VersionUnsupported     bool
	Installed              bool
	Version                string
	Running                bool
}

// NewFakeProvider creates a fake provider with defaults.
func NewFakeProvider(name, protocol string) *FakeProvider {
	return &FakeProvider{
		ProviderName:   name,
		Protocol:       protocol,
		Installed:      true,
		Version:        "1.0.0",
		Running:        true,
		ProvConfigPath: "/tmp/fake-config.conf",
	}
}

// State implements provider.Provider.
func (fp *FakeProvider) State() provider.ProviderState {
	s := provider.ProviderState{
		ID:           fp.ProviderName,
		Name:         fp.ProviderName,
		GatewayType:  provider.TypeHTTPTerm,
		Status:       "ready",
		ConfigPath:   fp.ProvConfigPath,
		BinaryPath:   "/usr/bin/" + fp.ProviderName,
		Installed:    fp.Installed && !fp.MissingBinary,
		Running:      fp.Running && !fp.MissingBinary,
		Version:      fp.Version,
		Capabilities: fp.fakeCapabilities(),
	}
	if !s.Installed || !s.Running {
		s.Status = "unavailable"
	}
	if fp.FailValidate || fp.ListenerConflict {
		s.Status = "degraded"
	}
	return s
}

// Diagnose implements provider.Provider.
func (fp *FakeProvider) Diagnose() provider.ProviderDiagnostic {
	diag := provider.ProviderDiagnostic{
		Provider:         fp.ProviderName,
		Installed:        fp.Installed && !fp.MissingBinary,
		BinaryPath:       "/usr/bin/" + fp.ProviderName,
		Version:          fp.Version,
		VersionSupported: !fp.VersionUnsupported,
		ConfigPath:       fp.ProvConfigPath,
		ConfigExists:     !fp.ConfigFileMissing,
		ListenerOK:       !fp.ListenerConflict,
	}

	if !fp.Installed || fp.MissingBinary {
		diag.LastErrorCode = provider.DiagCodeProviderMissing
		diag.LastErrorMessage = fmt.Sprintf("%s binary not found in PATH", fp.ProviderName)
		return diag
	}

	if fp.VersionUnsupported {
		diag.LastErrorCode = provider.DiagCodeVersionUnsupported
		diag.LastErrorMessage = fmt.Sprintf("version %s is below minimum required", fp.Version)
		return diag
	}

	if fp.ConfigFileMissing {
		diag.LastErrorCode = provider.DiagCodeConfigFileMissing
		diag.LastErrorMessage = fmt.Sprintf("config file not found: %s", fp.ProvConfigPath)
		return diag
	}

	if fp.FailValidate {
		valid := false
		diag.ConfigValid = &valid
		diag.LastErrorCode = provider.DiagCodeConfigValidateFailed
		diag.LastErrorMessage = fp.ValidateErr
		diag.Stderr = fmt.Sprintf("Error: %s", fp.ValidateErr)
		return diag
	}

	valid := true
	diag.ConfigValid = &valid

	if fp.ListenerConflict {
		diag.LastErrorCode = provider.DiagCodeListenerConflict
		diag.LastErrorMessage = fp.ListenerConflictDetail
		diag.ListenerOK = false
		return diag
	}

	if !fp.Running {
		running := false
		diag.ServiceRunning = &running
		diag.LastErrorCode = provider.DiagCodeServiceNotRunning
		diag.LastErrorMessage = "service is not running"
		return diag
	}

	running := true
	diag.ServiceRunning = &running

	if fp.RuntimeVerifyFailed {
		diag.LastErrorCode = provider.DiagCodeRuntimeVerifyFailed
		diag.LastErrorMessage = fp.RuntimeVerifyErr
		diag.Stderr = fp.RuntimeVerifyErr
		return diag
	}

	diag.ListenerOK = true
	return diag
}

// Render implements provider.Provider. Generates reverse_proxy directives with headers.
func (fp *FakeProvider) Render(plan provider.Plan) ([]provider.ConfigFile, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by FakeProvider for testing\n")
	for _, r := range plan.Routes {
		buf.WriteString(fmt.Sprintf("%s {\n", r.Match.Host))
		buf.WriteString("    encode gzip\n")
		if len(r.ExtraHeaders) > 0 {
			buf.WriteString(fmt.Sprintf("    reverse_proxy %s {\n", r.Upstream.Target))
			for k, v := range r.ExtraHeaders {
				buf.WriteString(fmt.Sprintf("        header_up %s \"%s\"\n", k, v))
			}
			buf.WriteString("    }\n")
		} else {
			buf.WriteString(fmt.Sprintf("    reverse_proxy %s\n", r.Upstream.Target))
		}
		buf.WriteString("}\n")
	}
	return []provider.ConfigFile{
		{Path: fp.ProvConfigPath, Content: buf.Bytes()},
	}, nil
}

// Apply implements provider.Provider.
func (fp *FakeProvider) Apply(configs []provider.ConfigFile) error {
	if fp.FailBackup {
		return fmt.Errorf("backup failed")
	}
	if fp.FailValidate {
		errMsg := fp.ValidateErr
		if errMsg == "" {
			errMsg = "syntax error at line 1"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeConfigValidateFailed, errMsg)
	}
	if fp.FailReload {
		errMsg := fp.ReloadErr
		if errMsg == "" {
			errMsg = "service not running"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeServiceNotRunning, errMsg)
	}
	if fp.RuntimeVerifyFailed {
		errMsg := fp.RuntimeVerifyErr
		if errMsg == "" {
			errMsg = "health check returned 502"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeRuntimeVerifyFailed, errMsg)
	}
	return nil
}

// ResetErrors clears all failure injection flags.
func (fp *FakeProvider) ResetErrors() {
	fp.MissingBinary = false
	fp.FailValidate = false
	fp.ValidateErr = ""
	fp.FailReload = false
	fp.ReloadErr = ""
	fp.FailBackup = false
	fp.FailRestore = false
	fp.RuntimeVerifyFailed = false
	fp.RuntimeVerifyErr = ""
	fp.ListenerConflict = false
	fp.ListenerConflictDetail = ""
	fp.ConfigFileMissing = false
	fp.VersionUnsupported = false
	fp.Installed = true
	fp.Running = true
}

// fakeCapabilities returns a minimal capability set for testing.
func (fp *FakeProvider) fakeCapabilities() []provider.Capability {
	return []provider.Capability{
		provider.CapListenTCP,
		provider.CapUpstreamTCP,
		provider.CapTLSTerminate,
		provider.CapHTTP1,
		provider.CapRouteHost,
		provider.CapRoutePath,
		provider.CapHotReload,
		provider.CapValidateConfig,
	}
}

// Ensure FakeProvider implements Provider
var _ provider.Provider = (*FakeProvider)(nil)

// ============================================================================
// Test helpers (not part of Provider interface)
// ============================================================================

// Validate returns an error based on failure injection flags.
// Test helper — not part of the Provider interface.
func (fp *FakeProvider) Validate(configPath string) error {
	if fp.ConfigFileMissing {
		return fmt.Errorf("%s: config file not found at %s", provider.DiagCodeConfigFileMissing, configPath)
	}
	if fp.FailValidate {
		errMsg := fp.ValidateErr
		if errMsg == "" {
			errMsg = "syntax error at line 1"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeConfigValidateFailed, errMsg)
	}
	if fp.ListenerConflict {
		detail := fp.ListenerConflictDetail
		if detail == "" {
			detail = "port 443 already in use"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeListenerConflict, detail)
	}
	return nil
}

// ConfigPath returns the fake config path. Test helper.
func (fp *FakeProvider) ConfigPath() string { return fp.ProvConfigPath }

// Info returns the provider state. Test helper — use State() for interface compliance.
func (fp *FakeProvider) Info() provider.ProviderState { return fp.State() }

// Reload simulates a reload. Test helper — not part of the Provider interface.
func (fp *FakeProvider) Reload() error {
	if fp.FailReload {
		errMsg := fp.ReloadErr
		if errMsg == "" {
			errMsg = "service not running"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeServiceNotRunning, errMsg)
	}
	if fp.RuntimeVerifyFailed {
		errMsg := fp.RuntimeVerifyErr
		if errMsg == "" {
			errMsg = "health check returned 502"
		}
		return fmt.Errorf("%s: %s", provider.DiagCodeRuntimeVerifyFailed, errMsg)
	}
	return nil
}

// ============================================================================
// FakeCluster — multi-node cluster simulation for testing
// ============================================================================

// FakeCluster simulates multi-node cluster scenarios for testing.
type FakeCluster struct {
	Nodes           []FakeNode
	ACKTimeout      bool
	SplitBrain      bool
	NoLeader        bool
	VersionMismatch bool
}

// FakeNode represents a simulated node in a cluster.
type FakeNode struct {
	NodeID       string
	IsLeader     bool
	IsCurrent    bool
	StateVersion uint64
	IsStale      bool
	LastSeen     string
	LocalIP      string
}

// NewFakeCluster creates a fake cluster with default healthy state.
func NewFakeCluster(nodeCount int) *FakeCluster {
	fc := &FakeCluster{}
	for i := 0; i < nodeCount; i++ {
		fc.Nodes = append(fc.Nodes, FakeNode{
			NodeID:       fmt.Sprintf("node-%d", i+1),
			IsCurrent:    i == 0,
			IsLeader:     i == 0,
			StateVersion: 100,
			LastSeen:     "2026-01-01T00:00:00Z",
			LocalIP:      "10.0.0.1",
		})
	}
	return fc
}

// GetLeader returns the leader node or nil.
func (fc *FakeCluster) GetLeader() *FakeNode {
	for i := range fc.Nodes {
		if fc.Nodes[i].IsLeader {
			return &fc.Nodes[i]
		}
	}
	return nil
}

// GetCurrent returns the current (local) node.
func (fc *FakeCluster) GetCurrent() *FakeNode {
	for i := range fc.Nodes {
		if fc.Nodes[i].IsCurrent {
			return &fc.Nodes[i]
		}
	}
	return nil
}

// InjectDrift creates a version gap on a non-leader node.
func (fc *FakeCluster) InjectDrift(nodeIndex int, versionDiff uint64) {
	if nodeIndex < len(fc.Nodes) {
		leader := fc.GetLeader()
		if leader != nil {
			fc.Nodes[nodeIndex].StateVersion = leader.StateVersion - versionDiff
		}
	}
}

// InjectSplitBrain sets a second node as leader.
func (fc *FakeCluster) InjectSplitBrain() {
	fc.SplitBrain = true
	if len(fc.Nodes) >= 2 {
		fc.Nodes[1].IsLeader = true
	}
}

// InjectStaleNode marks a node as stale.
func (fc *FakeCluster) InjectStaleNode(nodeIndex int) {
	if nodeIndex < len(fc.Nodes) {
		fc.Nodes[nodeIndex].IsStale = true
		fc.Nodes[nodeIndex].LastSeen = "2025-01-01T00:00:00Z"
	}
}

// InjectVersionMismatch creates version differences across all nodes.
func (fc *FakeCluster) InjectVersionMismatch() {
	fc.VersionMismatch = true
	for i := range fc.Nodes {
		fc.Nodes[i].StateVersion = uint64(100 - i*10)
	}
}

// CheckDrift reports drift severity between two nodes.
func (fc *FakeCluster) CheckDrift(nodeA, nodeB int) string {
	vA := fc.Nodes[nodeA].StateVersion
	vB := fc.Nodes[nodeB].StateVersion
	diff := vA - vB
	if diff > vB {
		diff = vB - vA
	}
	if diff > 5 {
		return "HIGH"
	} else if diff > 1 {
		return "MEDIUM"
	} else if diff > 0 {
		return "LOW"
	}
	return "NONE"
}
