package dns

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

// DnsmasqConfig generates a dnsmasq configuration from the resolution table.
// Replaces the in-process UDP server — dnsmasq runs as an independent systemd service.
// Aegis stops, dnsmasq continues serving DNS. Same pattern as Caddy/HAProxy.
type DnsmasqConfig struct {
	ConfigPath    string   // e.g. "/etc/dnsmasq.d/aegis.conf"
	Upstream      string   // e.g. "1.1.1.1"
	ReloadCmd     string   // e.g. "systemctl reload dnsmasq"
}

// Render generates a dnsmasq config file from the given DNS entries.
// Format:
//   address=/domain1/internal_ip      ← managed domains
//   address=/domain2/internal_ip
//   server=1.1.1.1                    ← upstream for everything else
func (d *DnsmasqConfig) Render(entries map[string]ResolvedEntry) error {
	var buf strings.Builder
	buf.WriteString("# Generated by Aegis — do not edit manually\n")
	buf.WriteString(fmt.Sprintf("server=%s\n", d.Upstream))

	// Sort domains for deterministic output.
	domains := make([]string, 0, len(entries))
	for d := range entries {
		domains = append(domains, d)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		e := entries[domain]
		if e.TargetIP == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("address=/%s/%s\n", e.Domain, e.TargetIP))
	}

	return os.WriteFile(d.ConfigPath, []byte(buf.String()), 0644)
}

// Reload signals dnsmasq to reload its configuration.
func (d *DnsmasqConfig) Reload() error {
	if d.ReloadCmd == "" {
		return nil
	}
	parts := strings.Fields(d.ReloadCmd)
	cmd := exec.Command(parts[0], parts[1:]...)
	return cmd.Run()
}
