package dns

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// DnsmasqConfig generates a dnsmasq configuration from the resolution table.
// Replaces the in-process UDP server — dnsmasq runs as an independent systemd service.
// Aegis stops, dnsmasq continues serving DNS. Same pattern as Caddy/HAProxy.
type DnsmasqConfig struct {
	ConfigPath    string   // e.g. "/etc/dnsmasq.d/aegis.conf"
	Upstream      string   // e.g. "1.1.1.1"
	ReloadCmd     string   // e.g. "systemctl reload dnsmasq"
}

// Render generates the dnsmasq config content for the given DNS entries.
// Format:
//   address=/domain1/internal_ip      ← managed domains
//   address=/domain2/internal_ip
//   server=1.1.1.1                    ← upstream for everything else
func (d *DnsmasqConfig) Render(entries map[string]ResolvedEntry) error {
	content, err := d.RenderString(entries)
	if err != nil {
		return err
	}
	return d.WriteConfig(content)
}

// RenderString returns the config content without touching the filesystem,
// so callers can detect changes before writing (avoids reload churn).
func (d *DnsmasqConfig) RenderString(entries map[string]ResolvedEntry) (string, error) {
	var buf strings.Builder
	buf.WriteString("# Generated by Aegis — do not edit manually\n")
	buf.WriteString(fmt.Sprintf("server=%s\n", d.Upstream))

	// Sort domains for deterministic output.
	domains := make([]string, 0, len(entries))
	for d := range entries {
		domains = append(domains, d)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		e := entries[domain]
		if e.TargetIP == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("address=/%s/%s\n", e.Domain, e.TargetIP))
	}

	return buf.String(), nil
}

// WriteConfig writes the rendered content to the config path.
func (d *DnsmasqConfig) WriteConfig(content string) error {
	// Ensure the parent directory exists (e.g. /var/lib/aegis/dnsmasq on a
	// fresh install) so a missing dir is never the reason a refresh fails.
	if dir := filepath.Dir(d.ConfigPath); dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("mkdir dnsmasq config dir: %w", err)
		}
	}

	return os.WriteFile(d.ConfigPath, []byte(content), 0644)
}

// Reload signals dnsmasq to reload its configuration.
func (d *DnsmasqConfig) Reload() error {
	if d.ReloadCmd == "" {
		return nil
	}
	parts := strings.Fields(d.ReloadCmd)
	cmd := exec.Command(parts[0], parts[1:]...)
	return cmd.Run()
}
