/**
 * API Bridge — all pages import from here.
 * v1.8L-10: mock mode removed. All calls go to the real Go backend.
 */
export {
  fetchDashboard,
  fetchNodes,
  fetchNodeDetail,
  fetchGateways,
  fetchGatewayDetail,
  fetchTopologyMatrix,
  fetchTopologyPath,
  fetchServices,
  fetchServiceDetail,
  fetchRoutes,
  fetchRouteDetail,
  fetchEndpoints,
  fetchEndpointDetail,
  fetchPolicies,
  fetchRoutingTable,
  previewRouting,
  validateRouting,
  fetchSyncStatus,
  fetchLocalGatewayStatus,
  fetchAcceptance,
  fetchJoinTokens,
  createJoinToken,
  revokeJoinToken,
  fetchSettings,
  updateSettings,
  fetchListeners,
  auth,
  system,
  safetyApi,
  traceApi,
  relayApi,
  gatewayApi,
  gatewayLinkApi,
  nodeApi,
  providerApi,
  exposureApi,
  adminApi,
  dnsApi,
  transparentApi,
  clusterHealthApi,
  portCheckApi,
  systemHealthApi,
  healthCheckApi,
  credentialApi,
  runtimeModeApi,
  compositionApi,
  routeApi,
  distnodeApi,
} from './real-api-client';
export type { RuntimeModeDef, RuntimeModeRole, RuntimeModeBinding, RuntimeAtom, AtomSlot, ProviderAtoms, Composition, CompDef } from './real-api-client';
