/**
 * Centralized status label/color mapping for all Aegis domain concepts.
 */
export const STATUS_LABEL: Record<string, string> = {
  // Node
  online: '在线',
  offline: '离线',
  degraded: '降级',
  unknown: '未知',
  // Sync
  in_sync: '已同步',
  outdated: '不同步',
  no_desired_state: '无期望状态',
  no_actual_state: '无实际状态',
  failed: '失败',
  // Route / Service / Endpoint
  active: '活跃',
  disabled: '禁用',
  error: '错误',
  pending: '待处理',
  revoked: '已撤销',
  // Health
  healthy: '健康',
  unhealthy: '异常',
  // Acceptance
  pass: '通过',
  fail: '失败',
  verified: '已验证',
  pending_label: '待验证',
  deferred: '已延期',
  // Gateway / Topology
  unreachable: '不可达',
  missing_link: '缺少 Link',
  missing_gateway: '缺少 Gateway',
  missing_gateway_link: '缺少 GatewayLink',
  // Routing
  available: '可用',
  unavailable: '不可用',
  policy_rejected: '策略拒绝',
  topology_unreachable: '拓扑不可达',
  public_not_allowed: '公网不允许',
  // Candidate mode
  local_gateway: '本机网关',
  private_gateway: '私网网关',
  public_gateway: '公网网关',
  // Policy mode
  auto: '自动',
  fixed: '固定',
  multi: '多路',
  // TLS
  http_only: '仅 HTTP',
  terminate_local: '本地终止',
  passthrough_deferred: '直通（延期）',
  // Capability
  fake_only: '仅模拟',
  doc_only: '仅文档',
  real_env_required: '需真实环境',
  // Verification
  code_verified: '代码验证',
  unit_verified: '单元验证',
  two_node_verified: '双节点已验证',
  real_two_node_verified: '双节点已验证',
  real_two_node_local_gateway_verified: '本机网关已验证',
  dev_entry_verified: '开发入口已验证',
  simulated_two_node_verified: '模拟双节点已验证',
  real_secret_runtime_code_verified: '密钥代码已验证',
  real_secret_runtime_deploy_pending: '密钥部署待验证',
  real_three_node_pending: '三节点待验证',
  https_deferred: 'HTTPS 延期',
  raw_tcp_deferred: 'TCP 延期',
  // Security
  safe: '安全',
  warning: '警告',
  blocked: '已阻止',
  // General
  ok: '正常',
  success: '成功',
};

export const STATUS_CLASS: Record<string, string> = {
  online: 'bg-[#4cd964]/20 text-[#4cd964]',
  offline: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  degraded: 'bg-[#e8b830]/20 text-[#e8b830]',
  unknown: 'bg-a-border/60 text-a-muted',
  in_sync: 'bg-[#4cd964]/20 text-[#4cd964]',
  outdated: 'bg-[#e8b830]/20 text-[#e8b830]',
  no_desired_state: 'bg-a-border/60 text-a-muted',
  no_actual_state: 'bg-a-border/60 text-a-muted',
  failed: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  active: 'bg-[#4cd964]/20 text-[#4cd964]',
  disabled: 'bg-[#e8b830]/20 text-[#e8b830]',
  error: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  pending: 'bg-[#e8b830]/20 text-[#e8b830]',
  revoked: 'bg-a-border/60 text-a-muted',
  healthy: 'bg-[#4cd964]/20 text-[#4cd964]',
  unhealthy: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  pass: 'bg-[#4cd964]/20 text-[#4cd964]',
  fail: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  pending_label: 'bg-[#e8b830]/20 text-[#e8b830]',
  deferred: 'bg-a-border/60 text-a-muted',
  unreachable: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  missing_link: 'bg-[#e8b830]/20 text-[#e8b830]',
  missing_gateway: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  missing_gateway_link: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  available: 'bg-[#4cd964]/20 text-[#4cd964]',
  unavailable: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  policy_rejected: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  topology_unreachable: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  public_not_allowed: 'bg-[#e8b830]/20 text-[#e8b830]',
  local_gateway: 'bg-a-accent/20 text-a-accent',
  private_gateway: 'bg-[#4cd964]/20 text-[#4cd964]',
  public_gateway: 'bg-[#e8b830]/20 text-[#e8b830]',
  fake_only: 'bg-[#e8b830]/20 text-[#e8b830]',
  code_verified: 'bg-a-accent/20 text-a-accent',
  two_node_verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  real_two_node_verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  real_two_node_local_gateway_verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  dev_entry_verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  simulated_two_node_verified: 'bg-[#4cd964]/20 text-[#4cd964]',
  real_secret_runtime_code_verified: 'bg-a-accent/20 text-a-accent',
  real_secret_runtime_deploy_pending: 'bg-[#e8b830]/20 text-[#e8b830]',
  real_three_node_pending: 'bg-[#e8b830]/20 text-[#e8b830]',
  https_deferred: 'bg-a-border/60 text-a-muted',
  raw_tcp_deferred: 'bg-a-border/60 text-a-muted',
  safe: 'bg-[#4cd964]/20 text-[#4cd964]',
  warning: 'bg-[#e8b830]/20 text-[#e8b830]',
  blocked: 'bg-[#ff5c72]/20 text-[#ff5c72]',
  ok: 'bg-[#4cd964]/20 text-[#4cd964]',
  success: 'bg-[#4cd964]/20 text-[#4cd964]',
};
