package proxy

import (
	"fmt"
	"strings"
)

// FakeAdapter implements ProxyAdapter for testing.
// DEPRECATED: use fake.FakeProvider + provider.Provider instead.
type FakeAdapter struct {
	name               string
	ValidateShouldFail bool
	ValidateErr        string
	RenderShouldFail   bool
	ReloadShouldFail   bool
	ReloadCallCount    int
}

// NewFakeAdapter creates a fake proxy adapter for testing.
// If no name is provided, defaults to "fake".
func NewFakeAdapter(name ...string) *FakeAdapter {
	n := "fake"
	if len(name) > 0 && name[0] != "" {
		n = name[0]
	}
	return &FakeAdapter{name: n}
}

func (fa *FakeAdapter) Name() string { return fa.name }

// Render generates a minimal Caddyfile from a GatewayConfig for testing.
// Produces actual reverse_proxy directives so e2e tests can verify routing logic.
func (fa *FakeAdapter) Render(gwCfg GatewayConfig) ([]byte, error) {
	if fa.RenderShouldFail {
		return nil, fmt.Errorf("fake render error")
	}

	var buf strings.Builder
	buf.WriteString("# Generated by FakeAdapter for testing\n")

	if gwCfg.Email != "" {
		buf.WriteString(fmt.Sprintf("# email: %s\n", gwCfg.Email))
	}
	if gwCfg.PortPolicyMode == "edge_mux" {
		buf.WriteString("# mode: edge_mux (Caddy :8443 internal)\n")
	}

	for _, r := range gwCfg.Routes {
		buf.WriteString(fmt.Sprintf("%s {\n", r.Domain))
		if r.MaintenanceEnabled {
			buf.WriteString(fmt.Sprintf("    respond \"%s\" 503\n", r.MaintenanceMessage))
			buf.WriteString("}\n")
			continue
		}
		buf.WriteString("    encode gzip\n")
		if r.PathPrefix != "" {
			pp := r.PathPrefix
			if !strings.HasSuffix(pp, "*") && !strings.HasSuffix(pp, "/*") {
				pp = strings.TrimSuffix(pp, "/") + "/*"
			}
			if r.Options.StripPrefix {
				buf.WriteString(fmt.Sprintf("    handle_path %s {\n", pp))
			} else {
				buf.WriteString(fmt.Sprintf("    handle %s {\n", pp))
			}
			writeFakeReverseProxy(&buf, r.UpstreamURL, r.Options.ExtraHeaders, "        ")
			buf.WriteString("    }\n")
		} else {
			writeFakeReverseProxy(&buf, r.UpstreamURL, r.Options.ExtraHeaders, "    ")
		}
		buf.WriteString("}\n")
	}

	return []byte(buf.String()), nil
}

func (fa *FakeAdapter) Validate(configPath string) error {
	if fa.ValidateShouldFail {
		errMsg := fa.ValidateErr
		if errMsg == "" {
			errMsg = "syntax error at line 1"
		}
		return fmt.Errorf("CONFIG_VALIDATE_FAILED: %s", errMsg)
	}
	return nil
}

func (fa *FakeAdapter) Reload(command string) error {
	fa.ReloadCallCount++
	if fa.ReloadShouldFail {
		return fmt.Errorf("SERVICE_NOT_RUNNING: service not running")
	}
	return nil
}

// writeFakeReverseProxy writes a reverse_proxy directive with optional headers.
func writeFakeReverseProxy(buf *strings.Builder, upstream string, headers map[string]string, indent string) {
	if len(headers) > 0 {
		buf.WriteString(fmt.Sprintf("%sreverse_proxy %s {\n", indent, upstream))
		for k, v := range headers {
			buf.WriteString(fmt.Sprintf("%s    header_up %s \"%s\"\n", indent, k, v))
		}
		buf.WriteString(fmt.Sprintf("%s}\n", indent))
	} else {
		buf.WriteString(fmt.Sprintf("%sreverse_proxy %s\n", indent, upstream))
	}
}
