// Package provider — HAProxy configuration rendering engine.
//
// This file translates a Plan (listeners + routes) into HAProxy config files.
// It is separated from haproxy.go (Provider lifecycle) to keep each file
// focused: haproxy.go manages the Provider lifecycle, haproxy_render.go
// generates configuration syntax.
//
// ## HAProxy config structure
//
// Main config (haproxy.cfg — TLS SNI passthrough on :443):
//
//   global / defaults
//   frontend fe_tls_443
//       bind 0.0.0.0:443
//       tcp-request inspect-delay 5s
//       use_backend be_<sni> if { req.ssl_sni -i <hostname> }
//       default_backend be_reject
//   backend be_<sni>
//       server target <upstream> check
//   backend be_reject
//       tcp-request content reject
//
// TCP config (haproxy_tcp.cfg — raw TCP port forwarding):
//
//   Per-port frontend/backend pairs for dedicated TCP services.

package provider

import (
	"fmt"
	"sort"
	"strings"
)

// ============================================================================
// Main config — TLS SNI passthrough
// ============================================================================

// renderMainConfig generates haproxy.cfg for TLS SNI passthrough on :443.
// Routes are matched by SNI hostname; no TLS decryption is performed.
func (p *HAProxyProvider) renderMainConfig(listeners []ListenerSpec, routes []RouteSpec) []byte {
	var buf strings.Builder

	buf.WriteString("# Generated by Aegis — HAProxy Provider\n")
	buf.WriteString("# Mode: TLS SNI passthrough (no TLS termination)\n")
	buf.WriteString("# DO NOT EDIT MANUALLY\n\n")

	buf.WriteString("global\n")
	buf.WriteString("    log stdout format raw local0\n\n")

	buf.WriteString("defaults\n")
	buf.WriteString("    log global\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    timeout connect 5s\n")
	buf.WriteString("    timeout client  60s\n")
	buf.WriteString("    timeout server  60s\n\n")

	// Frontend for TLS SNI on 443
	buf.WriteString("frontend fe_tls_443\n")
	buf.WriteString("    bind 0.0.0.0:443\n")
	buf.WriteString("    mode tcp\n\n")
	buf.WriteString(fmt.Sprintf("    tcp-request inspect-delay %s\n", p.inspectDelay))
	buf.WriteString("    tcp-request content accept if { req_ssl_hello_type 1 }\n\n")

	// Sort SNI routes for stable output
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Match.SNI < routes[j].Match.SNI
	})

	for _, r := range routes {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(r.Match.SNI)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("    use_backend %s if { req.ssl_sni -i %s }\n", backendName, r.Match.SNI))
	}

	if len(routes) == 0 {
		buf.WriteString("    # No SNI rules configured — all traffic rejected\n")
	}
	buf.WriteString("\n    default_backend be_reject\n\n")

	// Backend blocks for each SNI route
	for _, r := range routes {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(r.Match.SNI)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("backend %s\n", backendName))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    server target %s check\n\n", r.Upstream.Target))
	}

	// Reject backend
	buf.WriteString("backend be_reject\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    tcp-request content reject\n")

	return []byte(buf.String())
}

// ============================================================================
// TCP config — raw port forwarding
// ============================================================================

// renderTCPConfig generates haproxy_tcp.cfg for raw TCP port forwarding.
// Each route gets its own frontend/backend pair on the route's specified port.
func (p *HAProxyProvider) renderTCPConfig(listeners []ListenerSpec, routes []RouteSpec) []byte {
	var buf strings.Builder

	buf.WriteString("# Generated by Aegis — HAProxy TCP Forwarding\n")
	buf.WriteString("# DO NOT EDIT MANUALLY\n\n")

	buf.WriteString("global\n")
	buf.WriteString("    log stdout format raw local0\n\n")

	buf.WriteString("defaults\n")
	buf.WriteString("    log global\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    timeout connect 5s\n")
	buf.WriteString("    timeout client  60s\n")
	buf.WriteString("    timeout server  60s\n\n")

	for _, r := range routes {
		port := r.Match.Port
		if port == 0 {
			// Derive port from listeners — use the first TCP listener
			for _, l := range listeners {
				if l.Protocol == "tcp" {
					port = l.Port
					break
				}
			}
			if port == 0 {
				continue // no TCP listener found, skip this route
			}
		}
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(fmt.Sprintf("tcp_%d", port))
		buf.WriteString(fmt.Sprintf("frontend fe_%s\n", safeName))
		buf.WriteString(fmt.Sprintf("    bind 0.0.0.0:%d\n", port))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    default_backend be_%s\n\n", safeName))

		buf.WriteString(fmt.Sprintf("backend be_%s\n", safeName))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    server target %s check\n\n", r.Upstream.Target))
	}

	return []byte(buf.String())
}
