package provider

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"aegis/internal/config"
	"aegis/internal/proxy"
)

// CaddyLayer4Provider wraps Caddy's layer4 module as a TCP/UDP port forwarding provider.
type CaddyLayer4Provider struct {
	cfg     *config.Config
	adapter *Layer4Adapter
}

// NewCaddyLayer4Provider creates a new Caddy layer4 provider.
func NewCaddyLayer4Provider(cfg *config.Config) *CaddyLayer4Provider {
	return &CaddyLayer4Provider{
		cfg:     cfg,
		adapter: &Layer4Adapter{},
	}
}

func (p *CaddyLayer4Provider) Info() Info {
	status := "ready"
	msg := ""
	if _, err := exec.LookPath(p.cfg.Proxy.CaddyBinary); err != nil {
		status = "degraded"
		msg = fmt.Sprintf("caddy binary not found: %v", err)
	}
	// Check if layer4 module is installed
	cmd := exec.Command(p.cfg.Proxy.CaddyBinary, "list-modules")
	out, err := cmd.Output()
	if err != nil || !strings.Contains(string(out), "layer4") {
		status = "degraded"
		if msg == "" {
			msg = "layer4 module not available"
		} else {
			msg += "; layer4 module not available"
		}
	}
	configPath := filepath.Join(filepath.Dir(p.cfg.Proxy.CaddyfilePath), "layer4.conf")
	return Info{
		Name:       "caddy_layer4",
		Protocol:   "tcp",
		Status:     status,
		Message:    msg,
		ConfigPath: configPath,
	}
}

func (p *CaddyLayer4Provider) Render(routes []proxy.RouteConfig) ([]byte, error) {
	if len(routes) == 0 {
		return []byte{}, nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by Aegis caddy_layer4 provider\n")
	buf.WriteString("# TCP/UDP port forwarding rules\n\n")

	for _, r := range routes {
		if r.Kind != "tcp_proxy" {
			continue
		}
		// Port determines the listener
		port := extractPort(r.UpstreamURL)
		listenPort := r.Domain // Port is stored as Domain in RouteConfig for layer4 routes
		if listenPort == "" {
			listenPort = fmt.Sprintf("%d", port)
		}

		buf.WriteString(fmt.Sprintf(":%s {\n", listenPort))
		buf.WriteString("    layer4 {\n")
		buf.WriteString(fmt.Sprintf("        proxy %s\n", r.UpstreamURL))
		buf.WriteString("    }\n")
		buf.WriteString("}\n\n")
	}
	return buf.Bytes(), nil
}

func (p *CaddyLayer4Provider) Validate(configPath string) error {
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return nil // No config to validate
	}
	cmd := exec.Command(p.cfg.Proxy.CaddyBinary, "validate", "--config", configPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy validate failed: %w\n%s", err, string(out))
	}
	return nil
}

func (p *CaddyLayer4Provider) Reload() error {
	configPath := filepath.Join(filepath.Dir(p.cfg.Proxy.CaddyfilePath), "layer4.conf")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return nil // No config to reload
	}
	// Use caddy reload (same binary, different config)
	cmd := exec.Command(p.cfg.Proxy.CaddyBinary, "reload", "--config", p.cfg.Proxy.CaddyfilePath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload failed: %w\n%s", err, string(out))
	}
	return nil
}

func (p *CaddyLayer4Provider) Backup() (string, error) {
	configPath := filepath.Join(filepath.Dir(p.cfg.Proxy.CaddyfilePath), "layer4.conf")
	data, err := os.ReadFile(configPath)
	if err != nil {
		return "", nil // No config to backup
	}
	tmpDir := os.TempDir()
	backupPath := filepath.Join(tmpDir, fmt.Sprintf("layer4_backup_%d.conf", time.Now().UnixNano()))
	if err := os.WriteFile(backupPath, data, 0644); err != nil {
		return "", fmt.Errorf("write layer4 backup: %w", err)
	}
	return backupPath, nil
}

func (p *CaddyLayer4Provider) Restore(backupPath string) error {
	data, err := os.ReadFile(backupPath)
	if err != nil {
		return fmt.Errorf("read layer4 backup: %w", err)
	}
	configPath := filepath.Join(filepath.Dir(p.cfg.Proxy.CaddyfilePath), "layer4.conf")
	return os.WriteFile(configPath, data, 0644)
}

func (p *CaddyLayer4Provider) GetCurrentConfig() (string, error) {
	configPath := filepath.Join(filepath.Dir(p.cfg.Proxy.CaddyfilePath), "layer4.conf")
	data, err := os.ReadFile(configPath)
	if err != nil {
		return "", nil
	}
	return string(data), nil
}

// Layer4Adapter adapts RouteConfig to Caddy layer4 syntax.
type Layer4Adapter struct{}

func (a *Layer4Adapter) Name() string { return "caddy_layer4" }

// extractPort extracts the port from an upstream URL like "127.0.0.1:3306" or "host:port".
func extractPort(upstream string) int {
	parts := strings.Split(upstream, ":")
	if len(parts) >= 2 {
		var port int
		fmt.Sscanf(parts[len(parts)-1], "%d", &port)
		return port
	}
	return 0
}
