package provider

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// HAProxyEdgeMuxProvider generates HAProxy config for TLS SNI passthrough on 443.
type HAProxyEdgeMuxProvider struct {
	configPath    string
	backupDir     string
	inspectDelay  string
}

// NewHAProxyEdgeMuxProvider creates an HAProxy EdgeMux provider.
func NewHAProxyEdgeMuxProvider(configPath, backupDir string) *HAProxyEdgeMuxProvider {
	if configPath == "" {
		configPath = "/etc/haproxy/haproxy.cfg"
	}
	if backupDir == "" {
		backupDir = "/var/lib/aegis/haproxy-backups"
	}
	return &HAProxyEdgeMuxProvider{
		configPath:   configPath,
		backupDir:    backupDir,
		inspectDelay: "5s",
	}
}

func (p *HAProxyEdgeMuxProvider) Name() string     { return "haproxy_edge_mux" }
func (p *HAProxyEdgeMuxProvider) Kind() string      { return "edge_mux" }
func (p *HAProxyEdgeMuxProvider) ConfigPath() string { return p.configPath }

// EdgeMuxEntry represents a single SNI routing entry.
type EdgeMuxEntry struct {
	SNIHost    string
	TargetHost string
	TargetPort int
	Kind       string
}

// Render generates HAProxy config for EdgeMux mode.
func (p *HAProxyEdgeMuxProvider) Render(entries []EdgeMuxEntry) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("# Generated by Aegis — HAProxy EdgeMux Provider\n")
	buf.WriteString("# Mode: TLS SNI passthrough (no TLS termination)\n")
	buf.WriteString("# DO NOT EDIT MANUALLY\n\n")

	buf.WriteString("global\n")
	buf.WriteString("    log stdout format raw local0\n\n")

	buf.WriteString("defaults\n")
	buf.WriteString("    log global\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    timeout connect 5s\n")
	buf.WriteString("    timeout client  60s\n")
	buf.WriteString("    timeout server  60s\n\n")

	buf.WriteString("frontend fe_tls_443\n")
	buf.WriteString("    bind 0.0.0.0:443\n")
	buf.WriteString("    mode tcp\n\n")
	buf.WriteString(fmt.Sprintf("    tcp-request inspect-delay %s\n", p.inspectDelay))
	buf.WriteString("    tcp-request content accept if { req_ssl_hello_type 1 }\n\n")

	// Sort entries for stable output
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].SNIHost < entries[j].SNIHost
	})

	for _, e := range entries {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(e.SNIHost)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("    use_backend %s if { req.ssl_sni -i %s }\n", backendName, e.SNIHost))
	}

	if len(entries) == 0 {
		buf.WriteString("    # No SNI rules configured — all traffic rejected\n")
	}
	buf.WriteString(fmt.Sprintf("\n    default_backend be_reject\n\n"))

	// Backend blocks
	for _, e := range entries {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(e.SNIHost)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("backend %s\n", backendName))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    server target %s:%d check\n\n", e.TargetHost, e.TargetPort))
	}

	// Reject backend
	buf.WriteString("backend be_reject\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    tcp-request content reject\n")

	return []byte(buf.String()), nil
}

func (p *HAProxyEdgeMuxProvider) Validate(configPath string) error {
	path := configPath
	if path == "" {
		path = p.configPath
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	cmd := exec.Command("haproxy", "-c", "-f", path)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy validate failed: %s\n%s", err.Error(), string(output))
	}
	return nil
}

func (p *HAProxyEdgeMuxProvider) Reload() error {
	cmd := exec.Command("systemctl", "reload", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		errMsg := string(output)
		hint := ""
		if strings.Contains(errMsg, "permission denied") || strings.Contains(errMsg, "Permission denied") ||
			strings.Contains(errMsg, "Interactive authentication required") {
			hint = "\nReload failed. Try running 'aegis apply' with sudo or configure service permissions."
		}
		// Try haproxy -sf fallback
		cmd2 := exec.Command("haproxy", "-f", p.configPath, "-sf", "$(pidof haproxy)")
		out2, err2 := cmd2.CombinedOutput()
		if err2 != nil {
			return fmt.Errorf("haproxy reload failed (systemctl): %s\nstderr: %s%s\nhaproxy -sf also failed: %s",
				err.Error(), errMsg, hint, string(out2))
		}
	}
	_ = output
	return nil
}

func (p *HAProxyEdgeMuxProvider) Backup() (string, error) {
	if _, err := os.Stat(p.configPath); os.IsNotExist(err) {
		return "", nil
	}
	timestamp := time.Now().Format("20060102_150405")
	name := fmt.Sprintf("haproxy.cfg.%s.bak", timestamp)
	path := filepath.Join(p.backupDir, name)
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		return "", err
	}
	os.MkdirAll(p.backupDir, 0755)
	if err := os.WriteFile(path, data, 0644); err != nil {
		return "", err
	}
	return path, nil
}

func (p *HAProxyEdgeMuxProvider) Restore(backupPath string) error {
	if backupPath == "" {
		return fmt.Errorf("no backup path")
	}
	data, err := os.ReadFile(backupPath)
	if err != nil {
		return err
	}
	return os.WriteFile(p.configPath, data, 0644)
}

func (p *HAProxyEdgeMuxProvider) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		if os.IsNotExist(err) { return "", nil }
		return "", err
	}
	return string(data), nil
}

func (p *HAProxyEdgeMuxProvider) Status() ProviderStatus {
	return CheckHAProxyStatus(p.configPath)
}

// Diagnose implements the Diagnoser interface for HAProxyEdgeMuxProvider.
func (p *HAProxyEdgeMuxProvider) Diagnose() ProviderDiagnostic {
	now := time.Now().Format(time.RFC3339)
	diag := ProviderDiagnostic{
		Provider:   "haproxy_edge_mux",
		ConfigPath: p.configPath,
		CheckedAt:  now,
	}

	// 1. Check binary
	haproxyPath, err := exec.LookPath("haproxy")
	if err != nil {
		diag.LastErrorCode = DiagCodeProviderMissing
		diag.LastErrorMessage = "haproxy binary not found in PATH"
		return diag
	}
	diag.Installed = true
	diag.BinaryPath = haproxyPath

	// 2. Get version
	verOut, verErr := exec.Command(haproxyPath, "-v").CombinedOutput()
	if verErr != nil {
		diag.Version = "unknown"
		diag.VersionSupported = false
		diag.LastErrorCode = DiagCodeVersionUnsupported
		diag.LastErrorMessage = fmt.Sprintf("haproxy version check failed: %v", verErr)
		diag.Stderr = string(verOut)
		return diag
	}
	diag.Version = strings.TrimSpace(string(verOut))
	major, minor := parseHAProxyVersionParts(diag.Version)
	diag.VersionSupported = major >= 2 || (major == 1 && minor >= 8)

	// 3. Check config file
	if _, statErr := os.Stat(p.configPath); os.IsNotExist(statErr) {
		diag.LastErrorCode = DiagCodeConfigFileMissing
		diag.LastErrorMessage = fmt.Sprintf("config file not found: %s", p.configPath)
		return diag
	}
	diag.ConfigExists = true

	// 4. Validate config
	validOut, validErr := exec.Command(haproxyPath, "-c", "-f", p.configPath).CombinedOutput()
	valid := validErr == nil
	diag.ConfigValid = &valid
	if !valid {
		diag.LastErrorCode = DiagCodeConfigValidateFailed
		diag.LastErrorMessage = fmt.Sprintf("haproxy -c failed for %s", p.configPath)
		diag.Stderr = string(validOut)
		return diag
	}

	// 5. Check service
	_, svcErr := exec.Command("systemctl", "is-active", "--quiet", "haproxy").CombinedOutput()
	running := svcErr == nil
	diag.ServiceRunning = &running
	if !running {
		diag.LastErrorCode = DiagCodeServiceNotRunning
		diag.LastErrorMessage = "haproxy systemd service is not active"
		return diag
	}

	diag.ListenerOK = true
	rtOK := true
	diag.RuntimeVerifyOK = &rtOK

	return diag
}

// Ensure HAProxyEdgeMuxProvider implements Diagnoser
var _ Diagnoser = (*HAProxyEdgeMuxProvider)(nil)
