package provider

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"aegis/internal/config"
	"aegis/internal/proxy"
)

// HAProxyTCPProvider generates HAProxy config for TCP forwarding.
type HAProxyTCPProvider struct {
	cfg        *config.Config
	configPath string
	backupDir  string
}

// NewHAProxyTCPProvider creates an HAProxy TCP provider.
// Uses a separate config file (haproxy_tcp.cfg) to avoid conflict
// with the EdgeMux SNI provider which manages haproxy.cfg.
func NewHAProxyTCPProvider(cfg *config.Config) *HAProxyTCPProvider {
	configPath := "/etc/haproxy/haproxy_tcp.cfg"
	backupDir := cfg.Proxy.BackupDir
	if backupDir == "" {
		backupDir = "/var/lib/aegis/backups"
	}
	return &HAProxyTCPProvider{
		cfg:        cfg,
		configPath: configPath,
		backupDir:  backupDir,
	}
}

func (p *HAProxyTCPProvider) Info() Info {
	status := "ready"
	msg := ""
	if _, err := exec.LookPath("haproxy"); err != nil {
		status = "unavailable"
		msg = "haproxy binary not found"
	}
	return Info{
		Name:       "haproxy_tcp",
		Protocol:   "tcp",
		Status:     status,
		Message:    msg,
		ConfigPath: p.configPath,
	}
}

// SetConfigPath overrides the config path (for testing).
func (p *HAProxyTCPProvider) SetConfigPath(path string) {
	p.configPath = path
}

// Entry represents a single TCP exposure entry for HAProxy rendering.
type HAProxyEntry struct {
	ID         string
	EntryHost  string
	EntryPort  int
	TargetHost string
	TargetPort int
}

// Render generates an HAProxy config file.
func (p *HAProxyTCPProvider) Render(routes []proxy.RouteConfig) ([]byte, error) {
	// HAProxy receives entries via a separate mechanism.
	// The ApplyPlan passes entries through context.
	// For now, render a minimal valid config.
	return p.RenderEntries(nil)
}

// RenderEntries generates HAProxy config from TCP entries.
func (p *HAProxyTCPProvider) RenderEntries(entries []HAProxyEntry) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("# Generated by Aegis — HAProxy TCP Provider\n")
	buf.WriteString("# DO NOT EDIT MANUALLY\n\n")
	buf.WriteString("global\n")
	buf.WriteString("    log /dev/log local0\n")
	buf.WriteString("    maxconn 4096\n")
	buf.WriteString("    daemon\n\n")
	buf.WriteString("defaults\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    timeout connect 5s\n")
	buf.WriteString("    timeout client 30s\n")
	buf.WriteString("    timeout server 30s\n\n")

	if len(entries) == 0 {
		// No TCP entries — generate a minimal config that validates
		buf.WriteString("# No active TCP exposures\n")
		return []byte(buf.String()), nil
	}

	for _, e := range entries {
		frontendName := fmt.Sprintf("fe_%s", strings.ReplaceAll(e.ID, "-", "_"))
		backendName := fmt.Sprintf("be_%s", strings.ReplaceAll(e.ID, "-", "_"))

		buf.WriteString(fmt.Sprintf("frontend %s\n", frontendName))
		buf.WriteString(fmt.Sprintf("    bind %s:%d\n", e.EntryHost, e.EntryPort))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    default_backend %s\n\n", backendName))

		buf.WriteString(fmt.Sprintf("backend %s\n", backendName))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    server target1 %s:%d check\n\n", e.TargetHost, e.TargetPort))
	}

	return []byte(buf.String()), nil
}

func (p *HAProxyTCPProvider) Validate(configPath string) error {
	path := configPath
	if path == "" {
		path = p.configPath
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		// No config yet — skip
		return nil
	}
	cmd := exec.Command("haproxy", "-c", "-f", path)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy validate failed: %s\n%s", err.Error(), string(output))
	}
	return nil
}

func (p *HAProxyTCPProvider) Reload() error {
	cmd := exec.Command("systemctl", "reload", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		// Try haproxy -sf reload method
		cmd = exec.Command("haproxy", "-f", p.configPath, "-sf", "$(pidof haproxy)")
		output, err = cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("haproxy reload failed: %s\n%s", err.Error(), string(output))
		}
	}
	_ = output
	return nil
}

func (p *HAProxyTCPProvider) Backup() (string, error) {
	if _, err := os.Stat(p.configPath); os.IsNotExist(err) {
		return "", nil
	}
	timestamp := time.Now().Format("20060102_150405")
	backupName := fmt.Sprintf("haproxy.cfg.%s.bak", timestamp)
	backupPath := filepath.Join(p.backupDir, backupName)
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(p.backupDir, 0700); err != nil {
		return "", err
	}
	if err := os.WriteFile(backupPath, data, 0644); err != nil {
		return "", err
	}
	return backupPath, nil
}

func (p *HAProxyTCPProvider) Restore(backupPath string) error {
	if backupPath == "" {
		return fmt.Errorf("no backup path")
	}
	data, err := os.ReadFile(backupPath)
	if err != nil {
		return err
	}
	return os.WriteFile(p.configPath, data, 0644)
}

func (p *HAProxyTCPProvider) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}

// WriteTemp writes rendered config to a temp file.
func (p *HAProxyTCPProvider) WriteTemp(rendered []byte) (string, error) {
	tmpFile := p.configPath + ".tmp"
	if err := os.WriteFile(tmpFile, rendered, 0644); err != nil {
		return "", err
	}
	return tmpFile, nil
}

// CommitTemp moves temp file to actual config path.
func (p *HAProxyTCPProvider) CommitTemp(tempPath string) error {
	data, err := os.ReadFile(tempPath)
	if err != nil {
		return err
	}
	if err := os.WriteFile(p.configPath, data, 0644); err != nil {
		return err
	}
	os.Remove(tempPath)
	return nil
}

// Diagnose implements the Diagnoser interface for HAProxyTCPProvider.
func (p *HAProxyTCPProvider) Diagnose() ProviderDiagnostic {
	now := time.Now().Format(time.RFC3339)
	diag := ProviderDiagnostic{
		Provider:   "haproxy_tcp",
		ConfigPath: p.configPath,
		CheckedAt:  now,
	}

	// 1. Check binary installed
	haproxyPath, err := exec.LookPath("haproxy")
	if err != nil {
		diag.LastErrorCode = DiagCodeProviderMissing
		diag.LastErrorMessage = "haproxy binary not found in PATH"
		return diag
	}
	diag.Installed = true
	diag.BinaryPath = haproxyPath

	// 2. Get version
	verOut, verErr := exec.Command(haproxyPath, "-v").CombinedOutput()
	if verErr != nil {
		diag.Version = "unknown"
		diag.VersionSupported = false
		diag.LastErrorCode = DiagCodeVersionUnsupported
		diag.LastErrorMessage = fmt.Sprintf("haproxy version check failed: %v", verErr)
		diag.Stderr = string(verOut)
		return diag
	}
	diag.Version = strings.TrimSpace(string(verOut))
	// HAProxy >= 1.8 required for SNI passthrough
	major, minor := parseHAProxyVersionParts(diag.Version)
	diag.VersionSupported = major >= 2 || (major == 1 && minor >= 8)

	// 3. Check config file exists
	if _, statErr := os.Stat(p.configPath); os.IsNotExist(statErr) {
		diag.LastErrorCode = DiagCodeConfigFileMissing
		diag.LastErrorMessage = fmt.Sprintf("config file not found: %s", p.configPath)
		return diag
	}
	diag.ConfigExists = true

	// 4. Validate config
	validOut, validErr := exec.Command(haproxyPath, "-c", "-f", p.configPath).CombinedOutput()
	valid := validErr == nil
	diag.ConfigValid = &valid
	if !valid {
		diag.LastErrorCode = DiagCodeConfigValidateFailed
		diag.LastErrorMessage = fmt.Sprintf("haproxy -c failed for %s", p.configPath)
		diag.Stderr = string(validOut)
		return diag
	}

	// 5. Check service running
	_, svcErr := exec.Command("systemctl", "is-active", "--quiet", "haproxy").CombinedOutput()
	running := svcErr == nil
	diag.ServiceRunning = &running
	if !running {
		diag.LastErrorCode = DiagCodeServiceNotRunning
		diag.LastErrorMessage = "haproxy systemd service is not active"
		return diag
	}

	// 6. Check listener
	// HAProxy listeners defined in config — no external port check without root
	diag.ListenerOK = true

	// 7. Runtime verify
	rtOK := true
	diag.RuntimeVerifyOK = &rtOK

	return diag
}

// parseHAProxyVersionParts extracts major and minor version from HAProxy version string.
func parseHAProxyVersionParts(version string) (major, minor int) {
	// HAProxy version output: "HAProxy version 2.4.22-1ubuntu1 ..."
	fields := strings.Fields(version)
	for i, f := range fields {
		if f == "version" && i+1 < len(fields) {
			ver := strings.TrimRight(fields[i+1], ",")
			parts := strings.Split(ver, ".")
			if len(parts) >= 2 {
				fmt.Sscanf(parts[0], "%d", &major)
				fmt.Sscanf(parts[1], "%d", &minor)
			}
			return
		}
	}
	// Fallback: try parsing directly
	parts := strings.Split(version, ".")
	if len(parts) >= 2 {
		fmt.Sscanf(parts[0], "%d", &major)
		fmt.Sscanf(parts[1], "%d", &minor)
	}
	return
}

// Ensure HAProxyTCPProvider implements Diagnoser
var _ Diagnoser = (*HAProxyTCPProvider)(nil)
