package provider

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// HAProxyEdgeMuxProvider generates HAProxy config for TLS SNI passthrough on 443.
type HAProxyEdgeMuxProvider struct {
	configPath    string
	backupDir     string
	inspectDelay  string
}

// NewHAProxyEdgeMuxProvider creates an HAProxy EdgeMux provider.
func NewHAProxyEdgeMuxProvider(configPath, backupDir string) *HAProxyEdgeMuxProvider {
	if configPath == "" {
		configPath = "/etc/haproxy/haproxy.cfg"
	}
	if backupDir == "" {
		backupDir = "/var/lib/aegis/haproxy-backups"
	}
	return &HAProxyEdgeMuxProvider{
		configPath:   configPath,
		backupDir:    backupDir,
		inspectDelay: "5s",
	}
}

func (p *HAProxyEdgeMuxProvider) Name() string     { return "haproxy_edge_mux" }
func (p *HAProxyEdgeMuxProvider) Kind() string      { return "edge_mux" }
func (p *HAProxyEdgeMuxProvider) ConfigPath() string { return p.configPath }

// EdgeMuxEntry represents a single SNI routing entry.
type EdgeMuxEntry struct {
	SNIHost    string
	TargetHost string
	TargetPort int
	Kind       string
}

// Render generates HAProxy config for EdgeMux mode.
func (p *HAProxyEdgeMuxProvider) Render(entries []EdgeMuxEntry) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("# Generated by Aegis — HAProxy EdgeMux Provider\n")
	buf.WriteString("# Mode: TLS SNI passthrough (no TLS termination)\n")
	buf.WriteString("# DO NOT EDIT MANUALLY\n\n")

	buf.WriteString("global\n")
	buf.WriteString("    log stdout format raw local0\n\n")

	buf.WriteString("defaults\n")
	buf.WriteString("    log global\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    timeout connect 5s\n")
	buf.WriteString("    timeout client  60s\n")
	buf.WriteString("    timeout server  60s\n\n")

	buf.WriteString("frontend fe_tls_443\n")
	buf.WriteString("    bind 0.0.0.0:443\n")
	buf.WriteString("    mode tcp\n\n")
	buf.WriteString(fmt.Sprintf("    tcp-request inspect-delay %s\n", p.inspectDelay))
	buf.WriteString("    tcp-request content accept if { req_ssl_hello_type 1 }\n\n")

	// Sort entries for stable output
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].SNIHost < entries[j].SNIHost
	})

	for _, e := range entries {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(e.SNIHost)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("    use_backend %s if { req.ssl_sni -i %s }\n", backendName, e.SNIHost))
	}

	if len(entries) == 0 {
		buf.WriteString("    # No SNI rules configured — all traffic rejected\n")
	}
	buf.WriteString(fmt.Sprintf("\n    default_backend be_reject\n\n"))

	// Backend blocks
	for _, e := range entries {
		safeName := strings.NewReplacer(".", "_", "-", "_").Replace(e.SNIHost)
		backendName := fmt.Sprintf("be_%s", safeName)
		buf.WriteString(fmt.Sprintf("backend %s\n", backendName))
		buf.WriteString("    mode tcp\n")
		buf.WriteString(fmt.Sprintf("    server target %s:%d check\n\n", e.TargetHost, e.TargetPort))
	}

	// Reject backend
	buf.WriteString("backend be_reject\n")
	buf.WriteString("    mode tcp\n")
	buf.WriteString("    tcp-request content reject\n")

	return []byte(buf.String()), nil
}

func (p *HAProxyEdgeMuxProvider) Validate(configPath string) error {
	path := configPath
	if path == "" {
		path = p.configPath
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	cmd := exec.Command("haproxy", "-c", "-f", path)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy validate failed: %s\n%s", err.Error(), string(output))
	}
	return nil
}

func (p *HAProxyEdgeMuxProvider) Reload() error {
	cmd := exec.Command("systemctl", "reload", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		cmd = exec.Command("haproxy", "-f", p.configPath, "-sf", "$(pidof haproxy)")
		output, err = cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("haproxy reload failed: %s\n%s", err.Error(), string(output))
		}
	}
	_ = output
	return nil
}

func (p *HAProxyEdgeMuxProvider) Backup() (string, error) {
	if _, err := os.Stat(p.configPath); os.IsNotExist(err) {
		return "", nil
	}
	timestamp := time.Now().Format("20060102_150405")
	name := fmt.Sprintf("haproxy.cfg.%s.bak", timestamp)
	path := filepath.Join(p.backupDir, name)
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		return "", err
	}
	os.MkdirAll(p.backupDir, 0755)
	if err := os.WriteFile(path, data, 0644); err != nil {
		return "", err
	}
	return path, nil
}

func (p *HAProxyEdgeMuxProvider) Restore(backupPath string) error {
	if backupPath == "" {
		return fmt.Errorf("no backup path")
	}
	data, err := os.ReadFile(backupPath)
	if err != nil {
		return err
	}
	return os.WriteFile(p.configPath, data, 0644)
}

func (p *HAProxyEdgeMuxProvider) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		if os.IsNotExist(err) { return "", nil }
		return "", err
	}
	return string(data), nil
}

func (p *HAProxyEdgeMuxProvider) Status() ProviderStatus {
	return CheckHAProxyStatus(p.configPath)
}
